const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
    },
});

/**
 * Sends agreement notification emails to both student and company,
 * with the agreement PDF attached.
 *
 * @param {object}  application   - Fully populated application document
 * @param {string}  studentEmail
 * @param {string}  companyEmail
 * @param {string}  appUrl
 * @param {Buffer}  pdfBuffer     - PDF bytes generated by generateAgreementPDF
 */
const sendAgreementEmails = async ({ application, studentEmail, companyEmail, appUrl, pdfBuffer }) => {
    const student     = application.studentId;
    const offer       = application.offerId;
    const company     = offer?.companyId;

    const studentName  = student?.name         || 'Student';
    const companyName  = company?.companyName  || 'Company';
    const offerTitle   = offer?.title          || 'Internship Position';
    const agreementUrl = `${appUrl}/agreement/${application._id}`;
    const verifyUrl    = `${appUrl}/verify-qr/${application._id}`;

    const pdfAttachment = pdfBuffer
        ? [{
            filename: `Internship_Agreement_${studentName.replace(/\s+/g, '_')}.pdf`,
            content:  pdfBuffer,
            contentType: 'application/pdf',
          }]
        : [];

    // ────────────────────────────────────────────────────────────────
    // Student Email
    // ────────────────────────────────────────────────────────────────
    const studentHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Your Internship Agreement</title>
</head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:'Segoe UI',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.07);">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#4f46e5 0%,#7c3aed 100%);padding:40px 40px 32px;">
            <span style="display:inline-block;background:rgba(255,255,255,0.15);color:#fff;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;padding:4px 12px;border-radius:100px;margin-bottom:16px;">Stag.io &nbsp;·&nbsp; Internship Platform</span>
            <h1 style="margin:0;color:#fff;font-size:28px;font-weight:800;line-height:1.2;">Your Internship Agreement<br/>is Ready! 🎉</h1>
            <p style="margin:12px 0 0;color:rgba(255,255,255,0.85);font-size:15px;">Congratulations <strong>${studentName}</strong>! Your internship has been officially validated.</p>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:40px;">

            <!-- PDF notice -->
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#eef2ff;border:1px solid #c7d2fe;border-radius:12px;margin-bottom:28px;">
              <tr>
                <td style="padding:20px 24px;">
                  <p style="margin:0 0 6px;font-size:13px;font-weight:700;color:#3730a3;">📎 Agreement PDF Attached</p>
                  <p style="margin:0;font-size:13px;color:#4338ca;line-height:1.6;">Your official internship agreement document is attached to this email as a PDF. Please save it for your records.</p>
                </td>
              </tr>
            </table>

            <!-- Details card -->
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4ff;border-radius:12px;margin-bottom:28px;">
              <tr>
                <td style="padding:24px;">
                  <p style="margin:0 0 4px;font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:1px;">Internship Details</p>
                  <p style="margin:0 0 16px;font-size:20px;font-weight:800;color:#1e293b;">${offerTitle}</p>
                  <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                      <td style="padding:6px 0;font-size:14px;color:#64748b;width:40%;">Host Company</td>
                      <td style="padding:6px 0;font-size:14px;color:#1e293b;font-weight:600;">${companyName}</td>
                    </tr>
                    <tr>
                      <td style="padding:6px 0;font-size:14px;color:#64748b;">Status</td>
                      <td style="padding:6px 0;"><span style="background:#dcfce7;color:#166534;font-size:12px;font-weight:700;padding:3px 10px;border-radius:100px;">✓ Validated</span></td>
                    </tr>
                    <tr>
                      <td style="padding:6px 0;font-size:14px;color:#64748b;">Agreement ID</td>
                      <td style="padding:6px 0;font-size:13px;color:#4f46e5;font-family:monospace;">AGR-${application._id}</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>

            <p style="margin:0 0 24px;font-size:15px;color:#475569;line-height:1.7;">
              Your agreement has been officially validated by the university administration.
              You can also view and download it online at any time using the button below.
            </p>

            <!-- CTA -->
            <table cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
              <tr>
                <td style="border-radius:10px;background:linear-gradient(135deg,#4f46e5,#7c3aed);">
                  <a href="${agreementUrl}" target="_blank" style="display:inline-block;padding:14px 32px;color:#fff;text-decoration:none;font-weight:700;font-size:15px;border-radius:10px;">View Agreement Online →</a>
                </td>
              </tr>
            </table>

            <!-- Verify -->
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#fefce8;border:1px solid #fde68a;border-radius:12px;margin-bottom:28px;">
              <tr>
                <td style="padding:20px 24px;">
                  <p style="margin:0 0 6px;font-size:13px;font-weight:700;color:#92400e;">🔐 Document Verification</p>
                  <p style="margin:0 0 10px;font-size:13px;color:#78350f;line-height:1.6;">Anyone can verify the authenticity of your agreement by scanning the QR code in the PDF or visiting:</p>
                  <a href="${verifyUrl}" style="font-size:12px;color:#4f46e5;word-break:break-all;">${verifyUrl}</a>
                </td>
              </tr>
            </table>

            <p style="margin:0;font-size:14px;color:#94a3b8;line-height:1.6;">Good luck with your internship! If you have any questions please contact your university internship office.</p>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#f8fafc;padding:24px 40px;border-top:1px solid #e2e8f0;text-align:center;">
            <p style="margin:0;font-size:12px;color:#94a3b8;">This email was sent automatically by <strong style="color:#4f46e5;">Stag.io</strong>. Please do not reply.</p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;

    // ────────────────────────────────────────────────────────────────
    // Company Email
    // ────────────────────────────────────────────────────────────────
    const companyHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Internship Agreement Confirmed</title>
</head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:'Segoe UI',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.07);">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%);padding:40px 40px 32px;">
            <span style="display:inline-block;background:rgba(255,255,255,0.1);color:#fff;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;padding:4px 12px;border-radius:100px;margin-bottom:16px;">Stag.io &nbsp;·&nbsp; Internship Platform</span>
            <h1 style="margin:0;color:#fff;font-size:28px;font-weight:800;line-height:1.2;">Internship Agreement<br/>Confirmed 📋</h1>
            <p style="margin:12px 0 0;color:rgba(255,255,255,0.7);font-size:15px;">An internship agreement has been validated for your company.</p>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:40px;">

            <!-- PDF notice -->
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;margin-bottom:28px;">
              <tr>
                <td style="padding:20px 24px;">
                  <p style="margin:0 0 6px;font-size:13px;font-weight:700;color:#166534;">📎 Agreement PDF Attached</p>
                  <p style="margin:0;font-size:13px;color:#15803d;line-height:1.6;">The official tripartite internship agreement is attached to this email. Please keep it for your company records.</p>
                </td>
              </tr>
            </table>

            <!-- Details card -->
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;border-radius:12px;margin-bottom:28px;">
              <tr>
                <td style="padding:24px;">
                  <p style="margin:0 0 4px;font-size:11px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:1px;">Agreement Summary</p>
                  <p style="margin:0 0 16px;font-size:20px;font-weight:800;color:#1e293b;">${offerTitle}</p>
                  <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                      <td style="padding:6px 0;font-size:14px;color:#64748b;width:40%;">Intern</td>
                      <td style="padding:6px 0;font-size:14px;color:#1e293b;font-weight:600;">${studentName}</td>
                    </tr>
                    <tr>
                      <td style="padding:6px 0;font-size:14px;color:#64748b;">University</td>
                      <td style="padding:6px 0;font-size:14px;color:#1e293b;font-weight:600;">${student?.university || 'N/A'}</td>
                    </tr>
                    <tr>
                      <td style="padding:6px 0;font-size:14px;color:#64748b;">Status</td>
                      <td style="padding:6px 0;"><span style="background:#dcfce7;color:#166534;font-size:12px;font-weight:700;padding:3px 10px;border-radius:100px;">✓ Validated by University</span></td>
                    </tr>
                    <tr>
                      <td style="padding:6px 0;font-size:14px;color:#64748b;">Agreement ID</td>
                      <td style="padding:6px 0;font-size:13px;color:#4f46e5;font-family:monospace;">AGR-${application._id}</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>

            <p style="margin:0 0 24px;font-size:15px;color:#475569;line-height:1.7;">
              The internship agreement for <strong>${studentName}</strong> has been officially validated by the university.
              The signed document is attached to this email and is also accessible online.
            </p>

            <!-- CTA -->
            <table cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
              <tr>
                <td style="border-radius:10px;background:#0f172a;">
                  <a href="${agreementUrl}" target="_blank" style="display:inline-block;padding:14px 32px;color:#fff;text-decoration:none;font-weight:700;font-size:15px;border-radius:10px;">View Agreement Online →</a>
                </td>
              </tr>
            </table>

            <p style="margin:0;font-size:14px;color:#94a3b8;line-height:1.6;">Please ensure all onboarding preparations are ready for the intern's arrival.</p>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#f8fafc;padding:24px 40px;border-top:1px solid #e2e8f0;text-align:center;">
            <p style="margin:0;font-size:12px;color:#94a3b8;">This email was sent automatically by <strong style="color:#4f46e5;">Stag.io</strong>. Please do not reply.</p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;

    const results = await Promise.allSettled([
        studentEmail && transporter.sendMail({
            from:        `"Stag.io Platform" <${process.env.EMAIL_USER}>`,
            to:          studentEmail,
            subject:     `🎉 Your Internship Agreement is Ready — ${offerTitle}`,
            html:        studentHtml,
            attachments: pdfAttachment,
        }),
        companyEmail && transporter.sendMail({
            from:        `"Stag.io Platform" <${process.env.EMAIL_USER}>`,
            to:          companyEmail,
            subject:     `📋 Internship Agreement Confirmed — ${studentName} @ ${offerTitle}`,
            html:        companyHtml,
            attachments: pdfAttachment,
        }),
    ]);

    results.forEach((result, i) => {
        const target = i === 0 ? 'student' : 'company';
        if (result.status === 'rejected') {
            console.error(`[Email] Failed to send to ${target}:`, result.reason?.message);
        } else {
            console.log(`[Email] Sent to ${target} with PDF attachment.`);
        }
    });
};

module.exports = { sendAgreementEmails };
